name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v3.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        cd build
        python build_exe.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: StreamlinkMaski-Windows
        path: StreamlinkMaski_v*.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          StreamlinkMaski_v*.zip
          ../dist/StreamlinkMaski.exe
        body_path: docs/RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract version info
      run: |
        VERSION=$(grep 'APP_VERSION = ' main.py | cut -d'"' -f2)
        echo "Building version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: Windows" >> $GITHUB_STEP_SUMMARY
        echo "- **Python**: 3.11" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Tool**: PyInstaller" >> $GITHUB_STEP_SUMMARY
